# Generated by Django 6.0.5 on 2026-05-07 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(max_length=7)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Stalled', 'Stalled'), ('Shipped', 'Shipped'), ('Archived', 'Archived')], default='Active', max_length=20)),
                ('stack', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocPage',
            fields=[
                ('id', models.SlugField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='api.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DevLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devlog', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('JS', 'JavaScript'), ('Python', 'Python'), ('TS', 'TypeScript'), ('Bash', 'Bash'), ('SQL', 'SQL'), ('Other', 'Other')], max_length=20)),
                ('code', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snippets', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('date_range', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('goal', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('capacity', models.IntegerField(default=0)),
                ('velocity', models.IntegerField(default=0)),
                ('completion', models.IntegerField(default=0)),
                ('carryover', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('Feature', 'Feature'), ('Bug', 'Bug'), ('Fix', 'Fix'), ('Chore', 'Chore'), ('Idea', 'Idea'), ('Docs', 'Docs')], max_length=20)),
                ('status', models.CharField(choices=[('Backlog', 'Backlog'), ('To do', 'To do'), ('In progress', 'In progress'), ('Blocked', 'Blocked'), ('In review', 'In review'), ('Done', 'Done')], default='Backlog', max_length=20)),
                ('priority', models.CharField(choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('points', models.IntegerField(default=1)),
                ('labels', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('pr_url', models.URLField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acceptance', models.JSONField(blank=True, default=list)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('steps', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.sprint')),
            ],
        ),
    ]
