# Generated by Django 6.0.5 on 2026-05-17 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_vault_password_hash_project_vault_timeout_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='GithubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.TextField()),
                ('github_username', models.CharField(blank=True, max_length=200)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
