# Generated by Django 6.0.5 on 2026-05-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='pending_mutations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
